name:                Chatter
version:             0.1.0.0
github:              "th3Dot/Chatter"
license:             BSD3
author:              "Martin Kalenda"
maintainer:          "email.kalenda@gmail.com"
copyright:           "2018 Martin Kalenda"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/Chatter#readme>

dependencies:
- base >= 4.7 && < 5
- network

library:
  source-dirs: src

executables:
  Chatter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Chatter

tests:
  Chatter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Chatter
